# Generated by Django 4.1.2 on 2022-10-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('full_name', models.CharField(max_length=30)),
                ('student_id', models.IntegerField()),
                ('job_title', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('linked_in', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
            ],
        ),
    ]
