# Generated by Django 4.0.6 on 2022-10-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_filter_alter_usermodel_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='job_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
