# Generated by Django 4.0.6 on 2022-10-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usermodel_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='job_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='linked_in',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
